server:
  port: 8090
spring:
  application:
    name: eureka-client-two
eureka:
  client:
    service-url:
      defaultZone: ${eureka-default-zone:http://localhost:8088/eureka}
  instance:
    hostname: eureka-client-two
